ALTER TABLE GHOST.WH1.SRVPR_PRINTLOG
	 ADD WORKSTATION VARCHAR(200) NULL
ALTER TABLE GHOST.WH2.SRVPR_PRINTLOG
	 ADD WORKSTATION VARCHAR(200) NULL
ALTER TABLE GHOST.WH3.SRVPR_PRINTLOG
	 ADD WORKSTATION VARCHAR(200) NULL


