DECLARE @DOCS VARCHAR(MAX)
SET @DOCS = '0002121118/F000518620#RFPackCaseCross#1|0002121129/F000518618#RFPackCaseCross#1'


if object_id('tempdb..#tmp') is not null drop table #tmp
SELECT 
	 --ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS IDENT,
	 --cast(SUBSTRING(ITEM,1,CASE WHEN CHARINDEX('#',ITEM)>0 THEN CHARINDEX('#',ITEM)-1 ELSE 0 END) as varchar(500)) AS DOCNUMBER,
	 --cast(SUBSTRING(ITEM,CHARINDEX('#',ITEM)+1, LEN(ITEM)) as varchar(500)) AS REPORTNAME
	 CAST(SUBSTRING(  ITEM, LEN(ITEM) - CHARINDEX('#',REVERSE(ITEM)) + 2 ,  CHARINDEX('#',REVERSE(ITEM))-1  ) as varchar(500)) AS GRP_DOC,
	 CAST(SUBSTRING(ITEM,  LEN(ITEM) - CHARINDEX('#',REVERSE(ITEM),CHARINDEX('#',REVERSE(ITEM))+1) + 2,  CHARINDEX('#',REVERSE(ITEM),CHARINDEX('#',REVERSE(ITEM))+1)-CHARINDEX('#',REVERSE(ITEM))-1  ) as varchar(500)) AS REPORTNAME,
	 CAST(SUBSTRING(ITEM,1, LEN(ITEM) - CHARINDEX('#',REVERSE(ITEM),CHARINDEX('#',REVERSE(ITEM))+1)) as varchar(500)) AS DOCNUMBER
into #tmp
FROM PRD1.DBO.SPLITLIST(@DOCS,'|')


SELECT 
D.GRP_DOC AS IDENT, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 0 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS ORIGINALS, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 0 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS COPIES, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 1 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS ORIGINALSEXPORTPDF, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 1 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS COPIESEXPORTPDF, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 2 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS ORIGINALSEXPORTXLS, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 2 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS COPIESEXPORTXLS 
FROM #tmp D
    LEFT JOIN SrvPr_PRINTLOG PL1 WITH(NOLOCK) ON PL1.DOCNUMBER=D.DOCNUMBER AND PL1.REPORTNAME=D.REPORTNAME
GROUP BY D.GRP_DOC ORDER BY D.GRP_DOC 


exec sp_executesql N'EXEC WH3.[SrvPr_PrintedDocsGet] @DOCS = @P1',N'@P1 text','0002121118/F000518620#RFPackCaseCross#1|0002121129/F000518618#RFPackCaseCross#1'