select code,[description] from wh3.codelkup with(nolock) where listname = 'LOTTABLE06' and code is not null 



select * from wh1.lotattribute where lottable06=''
select * from wh2.lotattribute where lottable06=''
select * from wh3.lotattribute where lottable06=''



DECLARE @DOCS TABLE(DOCNUM VARCHAR(50), REPNAME VARCHAR(100), IDENT INT, WAREHOUSE VARCHAR(15)) 
            INSERT INTO @DOCS 
        SELECT '0001077364/1','PackCase', 0,'WH1' UNION 
        SELECT '0001077459/1','PackCase', 1,'WH1'
select * from @DOCS
SELECT D.IDENT, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 0 THEN PL1.PRINTAMOUNT ELSE CASE WHEN ISNULL(PL2.REPORTNAME,'')<>'' AND PL2.ORIGINAL = 1 AND PL2.PRINTFORMAT = 0 THEN PL2.PRINTAMOUNT ELSE 0 END END),0) AS ORIGINALS, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 0 THEN PL1.PRINTAMOUNT ELSE CASE WHEN ISNULL(PL2.REPORTNAME,'')<>'' AND PL2.ORIGINAL = 0 AND PL2.PRINTFORMAT = 0 THEN PL2.PRINTAMOUNT ELSE 0 END END),0) AS COPIES, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 1 THEN PL1.PRINTAMOUNT ELSE CASE WHEN ISNULL(PL2.REPORTNAME,'')<>'' AND PL2.ORIGINAL = 1 AND PL2.PRINTFORMAT = 1 THEN PL2.PRINTAMOUNT ELSE 0 END END),0) AS ORIGINALSEXPORTPDF, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 1 THEN PL1.PRINTAMOUNT ELSE CASE WHEN ISNULL(PL2.REPORTNAME,'')<>'' AND PL2.ORIGINAL = 0 AND PL2.PRINTFORMAT = 1 THEN PL2.PRINTAMOUNT ELSE 0 END END),0) AS COPIESEXPORTPDF, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 2 THEN PL1.PRINTAMOUNT ELSE CASE WHEN ISNULL(PL2.REPORTNAME,'')<>'' AND PL2.ORIGINAL = 1 AND PL2.PRINTFORMAT = 2 THEN PL2.PRINTAMOUNT ELSE 0 END END),0) AS ORIGINALSEXPORTXLS, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 2 THEN PL1.PRINTAMOUNT ELSE CASE WHEN ISNULL(PL2.REPORTNAME,'')<>'' AND PL2.ORIGINAL = 0 AND PL2.PRINTFORMAT = 2 THEN PL2.PRINTAMOUNT ELSE 0 END END),0) AS COPIESEXPORTXLS 
FROM  @DOCS D 
    LEFT JOIN WH1.SrvPr_PRINTLOG PL1 WITH(NOLOCK) ON PL1.DOCNUMBER=D.DOCNUM AND PL1.REPORTNAME=D.REPNAME AND D.WAREHOUSE='WH1' 
    LEFT JOIN WH2.SrvPr_PRINTLOG PL2 WITH(NOLOCK) ON PL2.DOCNUMBER=D.DOCNUM AND PL2.REPORTNAME=D.REPNAME AND D.WAREHOUSE='WH2' 
    GROUP BY D.IDENT ORDER BY D.IDENT 
    
    

DECLARE @DOCS TABLE(DOCNUM VARCHAR(50), REPNAME VARCHAR(100), IDENT INT, WAREHOUSE VARCHAR(15)) 
            INSERT INTO @DOCS 
        SELECT '0001077364/1','PackCase', 0,'WH1' UNION 
        SELECT '0001077459/1','PackCase', 1,'WH1'
select * from @DOCS
SELECT D.IDENT, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 0 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS ORIGINALS, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 0 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS COPIES, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 1 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS ORIGINALSEXPORTPDF, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 1 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS COPIESEXPORTPDF, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 2 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS ORIGINALSEXPORTXLS, 
    ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 2 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS COPIESEXPORTXLS 
FROM  @DOCS D 
    LEFT JOIN WH1.SrvPr_PRINTLOG PL1 WITH(NOLOCK) ON PL1.DOCNUMBER=D.DOCNUM AND PL1.REPORTNAME=D.REPNAME 
    GROUP BY D.IDENT ORDER BY D.IDENT 


DECLARE @DOCS VARCHAR(MAX)
SET @DOCS = '0001077364/1#PackCase|0001077459/1#PackCase'
SELECT * FROM [WH1].[SrvPr_PRINTLOG_VIEW] (@DOCS,null, null,null,null, null, null)
SELECT REPORTNAME,REPORTCAPTION FROM DBO.SrvPr_REPORTS
REPORTNAME	REPORTCAPTION
7_Inv_All	07._Итоги_инвентаризации_общая

DECLARE @DOCS VARCHAR(MAX)
SET @DOCS = '0001077364/1#PackCase|0001077459/1#PackCase'
EXEC [WH1].[SrvPr_PRINTLOG_VIEW] @DOCS


select * from [db_report].[dbo].[T_GH_SCRT_OBJECT]

SELECT REPORTNAME,REPORTCAPTION FROM DBO.SrvPr_REPORTS
declare @DOCSREPORTS nvarchar(43),@DOCS nvarchar(4000),@REPORTS nvarchar(12),@DateFrom nvarchar(4000),@DateTo nvarchar(4000),@UserPrint nvarchar(4000),@WORKSTATION nvarchar(4000)
select @DOCSREPORTS=N'0001077364/1#PackCase|0001077459/1#PackCase',@DOCS=N'',@REPORTS=N'PackCase',@DateFrom=NULL,@DateTo=NULL,@UserPrint=NULL,@WORKSTATION=NULL
EXEC [WH1].[SrvPr_PRINTLOG_VIEW] 
@DOCSREPORTS,
@DOCS,
@REPORTS,
@DateFrom,
@DateTo,
@UserPrint,
@WORKSTATION




	 DECLARE @DOCSREPORTS VARCHAR(MAX)
	 SET @DOCSREPORTS = '0001077364/1#PackCase|0001077459/1#PackCase'
	 DECLARE @DOCS VARCHAR(MAX),@REPORTS VARCHAR(MAX),@DateFrom datetime,@DateTo datetime,@UserName [varchar](100),@WORKSTATION [varchar](200)
	 DECLARE @TBL_DOCSREPORTS TABLE(IDENT INT, DOCNUMBER  [varchar](100), REPORTNAME [varchar](100))
	 DECLARE @TBL_DOCS TABLE(DOCNUMBER [varchar](100))
	 DECLARE @TBL_REPORTS TABLE(REPORTNAME [varchar](100))

	 IF ISNULL(@DOCSREPORTS,'') <> ''
		  INSERT INTO @TBL_DOCSREPORTS (IDENT, DOCNUMBER, REPORTNAME)
		  SELECT 
				ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS IDENT,
				SUBSTRING(ITEM,1,CASE WHEN CHARINDEX('#',ITEM)>0 THEN CHARINDEX('#',ITEM)-1 ELSE 0 END) AS DOCNUMBER,
				SUBSTRING(ITEM,CHARINDEX('#',ITEM)+1, LEN(ITEM)) AS REPORTNAME
		  FROM PRD1.DBO.SPLITLIST(@DOCSREPORTS,'|')

		  	SELECT 
	 PL.[SERIALKEY],PL.[REPORTNAME],PL.[DOCNUMBER],PL.[ORIGINAL],PL.[PRINTAMOUNT],PL.[PRINTFORMAT], PL.[FORCEDCOPY],PL.[ADDWHO],PL.[ADDDATE],PL.[EDITWHO],PL.[EDITDATE],PL.[WORKSTATION]
	FROM 
	WH1.SrvPr_PRINTLOG PL WITH(NOLOCK)
		 INNER JOIN (SELECT * FROM @TBL_DOCSREPORTS) DOCSREPORTS ON DOCSREPORTS.DOCNUMBER=PL.DOCNUMBER AND DOCSREPORTS.REPORTNAME=PL.REPORTNAME
	WHERE 
		  (@DOCSREPORTS IS NULL OR DOCSREPORTS.DOCNUMBER IS NOT NULL)
		  AND (@DOCS IS NULL OR PL.[DOCNUMBER] IN (SELECT [DOCNUMBER] FROM @TBL_DOCS))
		  AND (@REPORTS IS NULL OR PL.[REPORTNAME] IN (SELECT [REPORTNAME] FROM @TBL_REPORTS))
		  AND (@DateFrom IS NULL OR PL.[ADDDATE] >= @DateFrom)
		  AND (@DateTo IS NULL OR 
						  ( 
								(@DateTo = DATEADD(DAY, DATEDIFF(DAY, 0, @DateTo), 0) and PL.[ADDDATE] < DATEADD(DAY, 1, @DateTo )) OR 
								(@DateTo <> DATEADD(DAY, DATEDIFF(DAY, 0, @DateTo), 0) and PL.[ADDDATE] <= @DateTo) 
						  ) 
				)
		  AND (@UserName IS NULL OR PL.[ADDWHO] LIKE '%' + @UserName + '%')
		  AND (@WORKSTATION IS NULL OR PL.[WORKSTATION] LIKE '%' + @WORKSTATION + '%')
select DATEADD(DAY, DATEDIFF(DAY, 0, getdate()), -3)
select DATEADD(DAY, DATEDIFF(DAY, 0, getdate()), 3)




update 
--select * from 
wh2.SrvPr_PRINTLOG
--set adddate = '20150901'
 where docnumber = '0002166985' and reportname = 'PickingList'




@DOCSREPORTS VARCHAR(MAX) = null,
@DOCS VARCHAR(MAX) = null,
@REPORTS VARCHAR(MAX) = null,
@DateFrom datetime = null,
@DateTo datetime = null,
@UserName datetime = null,
@WORKSTATION [varchar](200) = null
--EXEC [WH1].[SrvPr_PrintedDocsGet] @DOCS
SELECT 
D.IDENT, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 0 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS ORIGINALS, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 0 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS COPIES, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 1 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS ORIGINALSEXPORTPDF, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 1 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS COPIESEXPORTPDF, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 1 AND PL1.PRINTFORMAT = 2 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS ORIGINALSEXPORTXLS, 
ISNULL(SUM(CASE WHEN ISNULL(PL1.REPORTNAME,'')<>'' AND PL1.ORIGINAL = 0 AND PL1.PRINTFORMAT = 2 THEN PL1.PRINTAMOUNT ELSE 0 END),0) AS COPIESEXPORTXLS 
FROM
	 (SELECT 
		  ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS IDENT,
		  SUBSTRING(ITEM,1,CASE WHEN CHARINDEX('#',ITEM)>0 THEN CHARINDEX('#',ITEM)-1 ELSE 0 END) AS DOCNUMBER,
		  SUBSTRING(ITEM,CHARINDEX('#',ITEM)+1, LEN(ITEM)) AS REPORTNAME
	 FROM PRD1.DBO.SPLITLIST(@DOCS,'|')
	 ) D
    LEFT JOIN wh1.SrvPr_PRINTLOG PL1 WITH(NOLOCK) ON PL1.DOCNUMBER=D.DOCNUMBER AND PL1.REPORTNAME=D.REPORTNAME
GROUP BY D.IDENT ORDER BY D.IDENT 