USE db_report
declare @OBJID_MAX int
declare @OBJID_OLD int
SET @OBJID_MAX = (select max(OBJID)+1 from T_GH_SCRT_OBJECT)
SET @OBJID_OLD = (select OBJID from T_GH_SCRT_OBJECT where OBJNAME='MenuKey_312')
DELETE FROM T_GH_SCRT_GROUP_OBJ  WHERE OBJID=@OBJID_OLD
DELETE FROM T_GH_SCRT_OBJECT  WHERE OBJNAME='MenuKey_312'
INSERT INTO T_GH_SCRT_OBJECT  (OBJPID, OBJNAME, TYPEID, DESCRIPTION, [ORDER]) VALUES  ('72','MenuKey_312', '1',' Настройка печатных форм SSRS', '3')
INSERT INTO T_GH_SCRT_GROUP_OBJ  (GROUPID, OBJID, ENABLED, VISIBLE) VALUES  ('Admin', @OBJID_MAX,'True', 'True')
