CREATE LOGIN [WHALL] WITH PASSWORD=N'WHALL', DEFAULT_DATABASE=[PRD1], DEFAULT_LANGUAGE=[British], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
GRANT SELECT ON [WH1].[SrvPr_PRINTLOG] TO [WHALL];
GRANT SELECT ON [WH2].[SrvPr_PRINTLOG] TO [WHALL];
GRANT SELECT ON [dbo].[SrvPr_REPORTS] TO [WHALL];
